### ISSUE TITLE
Exception on app start on Nexus 5 (4.4.4, API Level 19)

### ISSUE THREAD

**Issue by hamorphis** [NativeScript/nativescript-marketplace-demo#108]
```
02-26 11:40:10.119: W/dalvikvm(28459): threadid=1: thread exiting with uncaught exception (group=0x4163aba8)
02-26 11:40:10.129: W/System.err(28459): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.examples/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
02-26 11:40:10.129: W/System.err(28459): Calling js method onCreateView failed
02-26 11:40:10.129: W/System.err(28459): Error: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
02-26 11:40:10.129: W/System.err(28459):     android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
02-26 11:40:10.129: W/System.err(28459):     android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
02-26 11:40:10.129: W/System.err(28459):     android.content.res.Resources.loadDrawable(Resources.java:2092)
02-26 11:40:10.129: W/System.err(28459):     android.content.res.Resources.getDrawable(Resources.java:700)
02-26 11:40:10.129: W/System.err(28459):     android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
02-26 11:40:10.129: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
02-26 11:40:10.129: W/System.err(28459):     java.lang.reflect.Constructor.constructNative(Native Method)
02-26 11:40:10.129: W/System.err(28459):     java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.createInstance(Platform.java:311)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.callJSMethodNative(Native Method)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:711)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:690)
02-26 11:40:10.129: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:680)
02-26 11:40:10.129: W/System.err(28459):     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l33_c42__.onCreateView(android.app.Fragment.java)
02-26 11:40:10.129: W/System.err(28459):     android.app.Fragment.performCreateView(Fragment.java:1700)
02-26 11:40:10.129: W/System.err(28459):     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
02-26 11:40:10.129: W/System.err(28459):     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
02-26 11:40:10.129: W/System.err(28459):     android.app.BackStackRecord.run(BackStackRecord.java:684)
02-26 11:40:10.129: W/System.err(28459):     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
02-26 11:40:10.129: W/System.err(28459):     android.app.Activity.performStart(Activity.java:5240)
02-26 11:40:10.129: W/System.err(28459):     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
02-26 11:40:10.129: W/System.err(28459):     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
02-26 11:40:10.129: W/System.err(28459):     android.app.ActivityThread.access$800(ActivityThread.java:135)
02-26 11:40:10.129: W/System.err(28459):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
02-26 11:40:10.129: W/System.err(28459):     android.os.Handler.dispatchMessage(Handler.java:102)
02-26 11:40:10.129: W/System.err(28459):     android.os.Looper.loop(Looper.java:136)
02-26 11:40:10.129: W/System.err(28459):     android.app.ActivityThread.main(ActivityThread.java:5001)
02-26 11:40:10.129: W/System.err(28459):     java.lang.reflect.Method.invokeNative(Native Method)
02-26 11:40:10.129: W/System.err(28459):     java.lang.reflect.Method.invoke(Method.java:515)
02-26 11:40:10.129: W/System.err(28459):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-26 11:40:10.129: W/System.err(28459):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-26 11:40:10.129: W/System.err(28459):     dalvik.system.NativeStart.main(Native Method)
02-26 11:40:10.129: W/System.err(28459): File: "/data/data/org.nativescript.examples/files/app/tns_modules/ui/action-bar/action-bar.js, line: 126, column: 24
02-26 11:40:10.129: W/System.err(28459): StackTrace: 
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'ActionBar._createUI', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/action-bar/action-bar.js', line: 126, column: 25
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 209, column: 14
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 165, column: 14
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'eachChild', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 170, column: 23
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/page/page-common.js', line: 247, column: 9
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 176, column: 18
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 143, column: 18
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'View._addView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view-common.js', line: 912, column: 14
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/frame/frame.js', line: 123, column: 11
02-26 11:40:10.129: W/System.err(28459): 	Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/frame/frame.js', line: 59, column: 17
02-26 11:40:10.129: W/System.err(28459): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
02-26 11:40:10.129: W/System.err(28459): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
02-26 11:40:10.129: W/System.err(28459): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
02-26 11:40:10.129: W/System.err(28459): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
02-26 11:40:10.129: W/System.err(28459): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 11:40:10.129: W/System.err(28459): 	at android.os.Looper.loop(Looper.java:136)
02-26 11:40:10.129: W/System.err(28459): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
02-26 11:40:10.129: W/System.err(28459): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-26 11:40:10.129: W/System.err(28459): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-26 11:40:10.129: W/System.err(28459): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-26 11:40:10.129: W/System.err(28459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-26 11:40:10.129: W/System.err(28459): 	at dalvik.system.NativeStart.main(Native Method)
02-26 11:40:10.129: W/System.err(28459): Caused by: com.tns.NativeScriptException: 
02-26 11:40:10.129: W/System.err(28459): Calling js method onCreateView failed
02-26 11:40:10.139: W/System.err(28459): Error: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
02-26 11:40:10.139: W/System.err(28459):     android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
02-26 11:40:10.139: W/System.err(28459):     android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
02-26 11:40:10.139: W/System.err(28459):     android.content.res.Resources.loadDrawable(Resources.java:2092)
02-26 11:40:10.139: W/System.err(28459):     android.content.res.Resources.getDrawable(Resources.java:700)
02-26 11:40:10.139: W/System.err(28459):     android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
02-26 11:40:10.139: W/System.err(28459):     android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
02-26 11:40:10.139: W/System.err(28459):     java.lang.reflect.Constructor.constructNative(Native Method)
02-26 11:40:10.139: W/System.err(28459):     java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.createInstance(Platform.java:311)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.callJSMethodNative(Native Method)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:711)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:690)
02-26 11:40:10.139: W/System.err(28459):     com.tns.Platform.callJSMethod(Platform.java:680)
02-26 11:40:10.139: W/System.err(28459):     com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l33_c42__.onCreateView(android.app.Fragment.java)
02-26 11:40:10.139: W/System.err(28459):     android.app.Fragment.performCreateView(Fragment.java:1700)
02-26 11:40:10.139: W/System.err(28459):     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
02-26 11:40:10.139: W/System.err(28459):     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
02-26 11:40:10.139: W/System.err(28459):     android.app.BackStackRecord.run(BackStackRecord.java:684)
02-26 11:40:10.139: W/System.err(28459):     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
02-26 11:40:10.139: W/System.err(28459):     android.app.Activity.performStart(Activity.java:5240)
02-26 11:40:10.139: W/System.err(28459):     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
02-26 11:40:10.139: W/System.err(28459):     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
02-26 11:40:10.139: W/System.err(28459):     android.app.ActivityThread.access$800(ActivityThread.java:135)
02-26 11:40:10.139: W/System.err(28459):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
02-26 11:40:10.139: W/System.err(28459):     android.os.Handler.dispatchMessage(Handler.java:102)
02-26 11:40:10.139: W/System.err(28459):     android.os.Looper.loop(Looper.java:136)
02-26 11:40:10.139: W/System.err(28459):     android.app.ActivityThread.main(ActivityThread.java:5001)
02-26 11:40:10.139: W/System.err(28459):     java.lang.reflect.Method.invokeNative(Native Method)
02-26 11:40:10.139: W/System.err(28459):     java.lang.reflect.Method.invoke(Method.java:515)
02-26 11:40:10.139: W/System.err(28459):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-26 11:40:10.139: W/System.err(28459):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-26 11:40:10.139: W/System.err(28459):     dalvik.system.NativeStart.main(Native Method)
02-26 11:40:10.139: W/System.err(28459): File: "/data/data/org.nativescript.examples/files/app/tns_modules/ui/action-bar/action-bar.js, line: 126, column: 24
02-26 11:40:10.139: W/System.err(28459): StackTrace: 
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'ActionBar._createUI', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/action-bar/action-bar.js', line: 126, column: 25
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 209, column: 14
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 165, column: 14
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'eachChild', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 170, column: 23
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/page/page-common.js', line: 247, column: 9
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'View._onAttached', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 176, column: 18
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view.js', line: 143, column: 18
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'View._addView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/core/view-common.js', line: 912, column: 14
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/frame/frame.js', line: 123, column: 11
02-26 11:40:10.139: W/System.err(28459): 	Frame: function:'android.app.Fragment.extend.onCreateView', file:'/data/data/org.nativescript.examples/files/app/tns_modules/ui/frame/frame.js', line: 59, column: 17
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.Platform.callJSMethodNative(Native Method)
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.Platform.callJSMethod(Platform.java:711)
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.Platform.callJSMethod(Platform.java:690)
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.Platform.callJSMethod(Platform.java:680)
02-26 11:40:10.139: W/System.err(28459): 	at com.tns.gen.android.app.Fragment_ftns_modules_ui_frame_frame_l33_c42__.onCreateView(android.app.Fragment.java)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.Fragment.performCreateView(Fragment.java:1700)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.BackStackRecord.run(BackStackRecord.java:684)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.Activity.performStart(Activity.java:5240)
02-26 11:40:10.139: W/System.err(28459): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
02-26 11:40:10.139: W/System.err(28459): 	... 11 more
02-26 11:40:10.139: W/System.err(28459): Caused by: java.lang.reflect.InvocationTargetException
02-26 11:40:10.139: W/System.err(28459): 	at java.lang.reflect.Constructor.constructNative(Native Method)
02-26 11:40:10.139: W/System.err(28459): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02-26 11:40:10.149: W/System.err(28459): 	at com.tns.Platform.createInstance(Platform.java:311)
02-26 11:40:10.149: W/System.err(28459): 	... 24 more
02-26 11:40:10.149: W/System.err(28459): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
02-26 11:40:10.149: W/System.err(28459): 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
02-26 11:40:10.149: W/System.err(28459): 	at android.content.res.Resources.getDrawable(Resources.java:700)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
02-26 11:40:10.149: W/System.err(28459): 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:192)
02-26 11:40:10.149: W/System.err(28459): 	... 27 more
02-26 11:40:10.149: W/System.err(28459): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
02-26 11:40:10.149: W/System.err(28459): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
02-26 11:40:10.149: W/System.err(28459): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
02-26 11:40:10.149: W/System.err(28459): 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
02-26 11:40:10.149: W/System.err(28459): 	... 35 more

```

**Comment by hamorphis** [comment]
http://android-developers.blogspot.bg/2016/02/android-support-library-232.html

1. Create a file `/app/App_Resources/Android/app.gradle` and paste this:
```
android {  
    defaultConfig {  
        generatedDensities = []
    }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }
}
```

2. Open `/platforms/android/build.gradle` and look for `com.android.tools.build:gradle:1.3.1`. Replace it with `com.android.tools.build:gradle:1.5.0`
