### ISSUE TITLE
Exception on Item reorder example

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/nativescript-marketplace-demo#201]
_Reproduced on:  Android devices_

Steps to Reproduce:
1. Open the app for the first time or resume after suspending
2. Navigate to "Item reorder" example
3. Tap and hold an item
Expected result: Nothing happens
Actual result: Exception is thrown

**Comment by vchimev** [comment]
Ping @ginev.

**Comment by PanayotCankov** [comment]
@pkoleva We can not reproduce this. We will need some help here.

**Comment by PanayotCankov** [comment]
Tap and hold - for very short duration (~ 1 sec.), move just a little but not too much, do not reorder. Crashes on drop in the same place.

**Comment by hamorphis** [comment]
```
05-25 15:35:01.713  2415  2415 D TNS.Java: Platform.CallJSMethod: calling js method onReorderFinished with javaObjectID 2783 type=com.tns.gen.com.telerik.widget.list.ItemReorderBehavior_ItemReorderListener_ftns_modules_nativescript-telerik-ui-pro_listview_listview_l715_c51__
05-25 15:35:01.714  2415  2415 D TNS.Native: CallJSMethodNative called javaObjectID=2783
05-25 15:35:01.714  2415  2415 D TNS.Native: CallJSMethodNative called jsObject=799397861
05-25 15:35:01.721  2415  2415 D TNS.Native: ObjectManager::GetJSInstanceInfo: called
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:713)
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:694)
05-25 15:35:01.722  2415  2415 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:684)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.callJSMethodNative(Native Method)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.callJSMethod(Runtime.java:713)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.callJSMethod(Runtime.java:694)
05-25 15:35:01.723  2415  2415 E ACRA    : 	at com.tns.Runtime.callJSMethod(Runtime.java:684)
```
