### ISSUE TITLE
Remove fresco, use plain Image

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-marketplace-demo#246]

**Comment by NickIliev** [comment]
Using plain `Image` with RadListView causes the following on Android 

```
System.err: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
System.err:     at org.nativescript.widgets.image.Fetcher.decodeSampledBitmapFromResource(Fetcher.java:389)
System.err:     at org.nativescript.widgets.image.Fetcher.processBitmap(Fetcher.java:268)
System.err:     at org.nativescript.widgets.image.Worker.loadImage(Worker.java:119)
System.err:     at org.nativescript.widgets.ImageView.loadImage(ImageView.java:197)
System.err:     at org.nativescript.widgets.ImageView.onAttachedToWindow(ImageView.java:58)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:15509)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:4456)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4258)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4198)
System.err:     at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:727)
System.err:     at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
System.err:     at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7921)
System.err:     at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7879)
System.err:     at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7867)
System.err:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
System.err:     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1316)
System.err:     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
System.err:     at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1727)
System.err:     at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2927)
System.err:     at com.telerik.widget.list.RadListView.onTouchEvent(RadListView.java:542)
System.err:     at android.view.View.dispatchTouchEvent(View.java:10023)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
System.err:     at android.view.View.dispatchPointerEvent(View.java:10243)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6320)
System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6372)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:615)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

package.json
```JSON
  "nativescript": {
    "id": "org.nativescript.examples",
    "tns-android": {
      "version": "4.2.0-2018-05-29-02"
    },
    "tns-ios": {
      "version": "4.1.0-2018-05-25-01"
    }
  },
  "dependencies": {
    "highlight.js": "~8.7.0",
    "nativescript-iqkeyboardmanager": "~1.3.0",
    "nativescript-plugin-firebase": "^6.0.2",
    "nativescript-tsx": "0.0.7",
    "nativescript-ui-chart": "~3.6.1",
    "nativescript-ui-dataform": "~3.6.0",
    "nativescript-ui-listview": "~3.5.7",
    "nativescript-ui-sidedrawer": "~4.1.0",
    "tns-core-modules": "next"
  },
```

**Comment by dtopuzov** [comment]
No more fresco.
