### ISSUE TITLE
App immediately crashes on Android 5.0

### ISSUE THREAD

**Issue by Menardi** [NativeScript/nativescript-marketplace-demo#84]
Just downloaded this from the Play Store and had it crash immediately.

Phone: Sony Xperia M4 Aqua (E2303)
Android Version: 5.0
App version: 1.3

I also downloaded it on a Nexus 5 running Android 6.0 and it works fine.

Here's some of the stack trace from adb logcat:
```
I/tfsw    (18467): Foreground was changed: org.nativescript.nativescriptmarketplacedemo
I/tfsw    (18467): Inform user attribute 0x0 [ 0.000000 0.000000 -1.000000 -1.000000 ]
W/ResourceType(19372): Found multiple library tables, ignoring...
I/art     (  864): Background sticky concurrent mark sweep GC freed 11210(574KB) AllocSpace objects, 7(156KB) LOS objects, 0% free, 52MB/52MB, paused 6.807ms total 91.061ms
D/AndroidRuntime(19372): Shutting down VM
E/AndroidRuntime(19372): FATAL EXCEPTION: main
E/AndroidRuntime(19372): Process: org.nativescript.nativescriptmarketplacedemo, PID: 19372
E/AndroidRuntime(19372): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.nativescriptmarketplacedemo-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.nativescriptmarketplacedemo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libNativeScript.so"
E/AndroidRuntime(19372): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(19372): 	at java.lang.System.loadLibrary(System.java:989)
E/AndroidRuntime(19372): 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:711)
E/AndroidRuntime(19372): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
E/AndroidRuntime(19372): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4611)
E/AndroidRuntime(19372): 	at android.app.ActivityThread.access$1500(ActivityThread.java:145)
E/AndroidRuntime(19372): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
E/AndroidRuntime(19372): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19372): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19372): 	at android.app.ActivityThread.main(ActivityThread.java:5319)
E/AndroidRuntime(19372): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19372): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19372): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
E/AndroidRuntime(19372): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
W/ActivityManager(  864):   Force finishing activity org.nativescript.nativescriptmarketplacedemo/com.tns.NativeScriptActivity
```

**Comment by Plamen5kov** [comment]
Hi @Menardi ,
Your phone has: `64-bit Qualcomm Snapdragon 615 Octa Core processor` and that leads me to believe, your system is trying to load the x64 libNativeScript.so, and we only distribute `arm` and `x86'. Your nexus 5 uses the first distribution of libNativeScript.so, and that's why it works.

**Comment by blagoev** [comment]
Hi @Menardi we have identified a problem with the application package and will be providing a fix for this. Thanks for reporting

**Comment by shprink** [comment]
Same with Nexus9 Android 6.0

**Comment by valentinstoychev** [comment]
Hey folks the updated app is now on play store.
